
server:      true
server_port: 4000

base-url:    'nevargames.com'
url:         https://nevargames.com/

include:     []
exclude:
  - _src
  - README.md

lsi:         false
pygments:    true
markdown:    rdiscount
permalink:   /blog/:year/:title
paginate:    16
