
server:      true
server_port: 4000

#base-url:    'localhost:4000'
#url:         https://localhost:4000/
base-url:    'amos.me'
url:         https://amos.me/

include:     []
exclude:
  - _src
  - README.md

lsi:         false
pygments:    true
markdown:    rdiscount
permalink:   /blog/:year/:title
paginate:    16
