
server:      true
server_port: 4000
baseurl:     /
url:         http://romac.me/nddrylliog-blog

include:     []
exclude:
  - _src
  - README.md

lsi:         false
pygments:    true
markdown:    rdiscount
permalink:   /blog/:year/:month/:day/:title
