
server:      true
server_port: 4000
baseurl:     /
url:         http://romac.me/wordshetypes

include:     []
exclude:     [ _src ]

lsi:         false
pygments:    true
markdown:    rdiscount
permalink:   /blog/:year/:month/:day/:title
